### ISSUE TITLE
Add external dictionary operations

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#141]
Sample rule
```yaml
Check:
  all:
    - operator: not_equal_to
      value: $valid_whodrug_codes
Operations:
 - id: $valid_whodrug_codes
   operator: whodrug_code_hierarchy
Rule Type: Record Data
Sensitivity: Record
```

Available operations:
- "valid_meddra_code_references" - Validates meddra codes.
- "valid_whodrug_references": Validates whodrug terms
- "whodrug_code_hierarchy": Validates whodrug codes are correct hierarchy
- "valid_meddra_term_references": Validates meddra terms
- "valid_meddra_code_term_pairs": Validates meddra terms match the supplied codes

AC:
Sample and available operations have been added to the documentation
Available operations have been added to the schema
